apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: myapp-argo-application # Name of the application.
  namespace: argocd # The namespace where the application should be created.
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    #argocd-image-updater.argoproj.io/git-branch: master
    #argocd-image-updater.argoproj.io/myapp.force-update: "true"
    argocd-image-updater.argoproj.io/image-list: devopsrakeshrestha/argocd:~1
    #argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/pull-secret: pullsecret:argocd/dockerhub-creds                              
spec:
  project: default
  source:
    repoURL: https://github.com/fusemachinesrakeshrestha/argocd # Remote Github repository where ArgoCD should pull configurations from.
    targetRevision: HEAD # The last commit in the remote repository.
    path: deployment # Track and sync the dev path in the repository.
  destination: 
    server: https://kubernetes.default.svc # Address of the Kubernetes cluster.
    namespace: argocd # Indicates that ArgoCD should apply the configurations from the git repository to the myapp namespace.

  syncPolicy:
    syncOptions:
    - CreateNamespace=true # Create the myapp namespace if it doesnt exits.

    automated:
      selfHeal: true # Automatically sync changes from the Git repository.
      prune: true
